name: Voter
on:
  pull_request:
  push:
    branches:
      - master
      
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3.1.0
      id: go
      with:
        go-version: 1.16
    - uses: actions/checkout@v2
    - name: Test Build
      run: |
        cd voter/voter && go get ./... && make install
